### ISSUE TITLE
unable to mock parts of asynctest after upgrading to 0.8.0

### ISSUE THREAD

**Issue by mozbhearsum** [Martiusweb/asynctest#25] opened 2016-08-31 16:55 UTC
This may be a dupe of #23, but...

I have code like this:

```
@asynctest.patch("balrogagent.client.request")
@asynctest.patch("balrogagent.cmd.telemetry_is_ready")
@asynctest.patch("balrogagent.cmd.time_is_ready")
class TestRunAgent(asynctest.TestCase):
    def setUp(self):
        self.loop = asyncio.get_event_loop()

    async def _runAgent(self, scheduled_changes, request):
        request.return_value = aiohttp.client.ClientResponse("GET", "http://balrog.fake/api/scheduled_changes")
        request.return_value.headers = {"Content-Type": "application/json"}
        body = {"count": len(scheduled_changes), "scheduled_changes": scheduled_changes}
        request.return_value._content = bytes(json.dumps(body), "utf-8")

        return await run_agent(self.loop, "http://balrog.fake", "balrog", "balrog", "telemetry", once=True, raise_exceptions=True)
```

...and with asynctest 0.8.0, I get fails such as:

```
E               TypeError: 'CoroutineMock' object is not subscriptable
```

However, everything works fine with asynctest 0.7.1, so it seems like it's an asynctest problem (or at least something asynctest can affect) rather than an aiohttp one.

**Comment by Martiusweb** [comment] 2016-08-31 17:15
Hm, several things changed around patches with 0.8.0.

At first glance, it doesn't look like exactly like a dupe of #23, but may be related to the scope on which patches are enabled for coroutines, or a bug when using the decorator on a class. Can you try using the argument `scope=asynctest.LIMITED` on `patch()`?

I will need more details to investigate: what is the object mocked by `CoroutineMock`? If possible, can I have the full traceback and the code of the mocked object (the one being called when the exception is raised)?

Also, since your test case inherits `asynctest.TestCase`, why do you need this `setUp()` method? `self.loop` is already set to a fresh loop (the one you retrieve with `get_event_loop()`) before a test method is executed.

**Comment by mozbhearsum** [comment] 2016-08-31 18:06
I'm mocking a few things, but the one that causes the error is the mock of balrogagent.client.request.

 Here's the full traceback:
```
_________________________________________________________________________________________________________________________ TestRunAgent.testNoChanges __________________________________________________________________________________________________________________________

self = <balrogagent.test.test_cmd.TestRunAgent testMethod=testNoChanges>, request = <MagicMock name='time_is_ready' id='140579364498736'>, telemetry_is_ready = <MagicMock name='telemetry_is_ready' id='140579357165888'>
time_is_ready = <CoroutineMock name='request' id='140579360168480'>

    async def testNoChanges(self, request, telemetry_is_ready, time_is_ready):
        sc = []
>       await self._runAgent(sc, request)

balrogagent/test/test_cmd.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
balrogagent/test/test_cmd.py:24: in _runAgent
    return await run_agent(self.loop, "http://balrog.fake", "balrog", "balrog", "telemetry", once=True, raise_exceptions=True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

loop = <_UnixSelectorEventLoop running=False closed=True debug=False>, balrog_api_root = 'http://balrog.fake', balrog_username = 'balrog', balrog_password = 'balrog', telemetry_api_root = 'telemetry', sleeptime = 30, once = True, raise_exceptions = True

    async def run_agent(loop, balrog_api_root, balrog_username, balrog_password, telemetry_api_root, sleeptime=30,
                        once=False, raise_exceptions=False):
        auth = aiohttp.BasicAuth(balrog_username, balrog_password)
    
        while True:
            try:
                logging.debug("Looking for active scheduled changes...")
                resp = await client.request(balrog_api_root, "/scheduled_changes/rules", auth=auth, loop=loop)
>               sc = (await resp.json())["scheduled_changes"]
E               TypeError: 'CoroutineMock' object is not subscriptable

balrogagent/cmd.py:20: TypeError
------------------------------------------------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------------------------------------------------
selector_events.py          53 DEBUG    Using selector: EpollSelector
cmd.py                      18 DEBUG    Looking for active scheduled changes...
cmd.py                      50 ERROR    Traceback (most recent call last):
  File "/home/bhearsum/repos/balrog/agent/balrogagent/cmd.py", line 20, in run_agent
    sc = (await resp.json())["scheduled_changes"]
TypeError: 'CoroutineMock' object is not subscriptable
```

The code is at https://github.com/mozbhearsum/balrog/tree/balrog-agent/agent. If you want to run it locally, clone it then run:
```
cd balrog/agent
# edit tox.ini to remove asynctest version pinning
tox
```

Setting scope as you suggest doesn't seem to change anything.

**Comment by Martiusweb** [comment] 2016-08-31 20:05
Oh! I've got it!

The order of the arguments has been reversed:

with 0.7.1:

    async def testNoChanges(self, request, telemetry_is_ready, time_is_ready):

with 0.8.0:

     async def testNoChanges(self, time_is_ready, telemetry_is_ready, request):

I have to check the behavior

**Comment by mozbhearsum** [comment] 2016-08-31 20:28
Ah! Thanks for the help in debugging that. I adjusted my tests and all is well with the latest version.

**Closed** 2016-11-02 10:19 UTC
Labels: documentation, enhancement
